---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ./prod_namespace.yaml
- ./role.yaml
- ./rolebinding.yaml
- ./cluster-config-secret.yaml  
- ./object-detection-app-git-buildconfig.yaml
- ./object-detection-app-git-imagestream.yaml  
- ./object-detection-app-git-deployment.yaml
- ./object-detection-app-git-route.yaml
- ./object-detection-app-git-service.yaml
- ./object-detection-rest-deployment.yaml
- ./object-detection-rest-route.yaml
- ./object-detection-rest-service.yaml
- ./retail-prod-app.yaml        
