---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ./retail-app.yaml        
- ./prod_namespace.yaml
- ./pvc-workspace.yaml
- ./role.yaml
- ./rolebinding.yaml
- ./cluster-config-secret.yaml  
- ./object-detection-app-git-buildconfig.yaml
- ./object-detection-app-git-imagestream.yaml
- ./object-detection-app-git-deployment.yaml
- ./object-detection-app-git-route.yaml
- ./object-detection-app-git-service.yaml
- ./object-detection-rest-buildconfig.yaml
- ./object-detection-rest-deployment.yaml
- ./object-detection-rest-route.yaml
- ./object-detection-rest-service.yaml
- ./pipeline-service-account.yaml
- ./object-detection-rest-pipeline.yaml
- ./trigger-template.yaml
- ./trigger-binding.yaml
- ./trigger-eventlistener.yaml
- ./el-route.yaml        
