---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ./prod_namespace.yaml
- ./pvc-workspace.yaml
- ./object-detection-app-git-buildconfig.yaml
- ./object-detection-app-git-imagestream.yaml
- ./object-detection-app-git-deployment.yaml
- ./object-detection-app-git-route.yaml
- ./object-detection-app-git-service.yaml
- ./object-detection-rest-buildconfig.yaml
- ./object-detection-rest-imagestream.yaml
- ./object-detection-rest-deployment.yaml
- ./object-detection-rest-route.yaml
- ./object-detection-rest-service.yaml
- ./object-detection-rest-pipeline.yaml
- ./object-detection-rest-pipeline-run.yaml
- ./trigger-template.yaml
- ./trigger-binding.yaml
- ./trigger-eventlistener.yaml
- ./el-route.yaml        

commonLabels:
  app: object-detect
